# Generated by Django 4.0.6 on 2023-07-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertypes',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='usertypes',
            name='cashier',
        ),
        migrations.RemoveField(
            model_name='usertypes',
            name='manager',
        ),
        migrations.AddField(
            model_name='usertypes',
            name='user_type',
            field=models.CharField(default='User', max_length=55),
            preserve_default=False,
        ),
    ]
